# 仿真环境配置
environment:
  env_name: "Lift"                    # 设置仿真环境
  robots: "Panda"                     # 设置机器人
  gripper_types: "Robotiq85Gripper"   # 夹爪类型
  control_freq: 30                    # 控制频率
  has_renderer: true                  # 是否使用渲染环境
  render_camera: "sideview"           # 哪个相机渲染
  has_offscreen_renderer: false       # 是否使用离线的渲染环境
  use_camera_obs: false               # 是否使用相机视角观测

# 相机配置
camera:
  names: ["frontview", "sideview", "robot0_robotview", "robot0_eye_in_hand"]  # 多视角离线渲染
  heights: 480  # 相机高度
  widths: 640   # 相机宽度
  depths: false # 是否需要渲染深度

# 控制器配置
controller:
  # 末端位姿控制器（默认使用，因为 robosuite 对此支持最好）
  default:
    type: "OSC_POSE"
    input_max: 1
    input_min: -1
    output_max: [0.05, 0.05, 0.05, 0.5, 0.5, 0.5]
    output_min: [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5]
    kp: 150
    damping: 1
    impedance_mode: "fixed"
    kp_limits: [0, 300]
    damping_limits: [0, 10]
    position_limits: null
    orientation_limits: null
    uncouple_pos_ori: true
    control_delta: true
    interpolation: null
    ramp_ratio: 0.2 # 控制参数

control:
  simulation_freq: 20  # 仿真循环频率 Hz
  default_mode: "joint_position"  # 默认控制模式
  action_limits:
    joint_position: 0.1  # 关节位置动作限制
    joint_velocity: 0.2  # 关节速度动作限制
    ee_position: 0.1     # 末端位置动作限制
    ee_velocity: 0.2     # 末端速度动作限制

# Franka 配置
franka_r7arm:
  host: "10.0.10.2"   # x = 0.500 , y =-0.000 , z = 0.500 , qx= 0.931 , qy=-0.364 , qz= 0.004 , qw= 0.003
  init_joint_angles: [0.238, -0.195, -0.209, -1.845, -0.049, 1.658, 1.568]

  position_ranges:
    x: [0.1, 0.8]
    y: [-0.5, 0.5]
    z: [0.1, 0.8]
  gripper_open_position: 85

# Oculus控制配置
oculus_control:
  control_frequency: 30.0        # 控制频率 Hz
  enable_recording: true          # 是否启用数据记录
  data_save_path: "data"          # 数据保存路径

  # 位姿缩放参数
  position_scale: 1.0             # 位置缩放系数（手柄移动1m，机械臂移动的距离）
  rotation_scale: 1.0             # 旋转缩放系数

  # 运动限制
  max_position_delta: 0.1         # 单步最大位置变化 (m)
  max_rotation_delta: 0.2         # 单步最大旋转变化 (rad)
