# robot_interface.py
from abc import ABC, abstractmethod
import numpy as np

class FrankyLike(ABC):
    @abstractmethod
    def connect(self): ...
    @abstractmethod
    def disconnect(self): ...
    @abstractmethod
    def set_dynamic_rel(self, factor: float): ...
    @abstractmethod
    def move_joint_target(self, q_target, duration: float): ...
    @abstractmethod
    def move_cartesian_relative(self, pos_delta, duration: float): ...
    @abstractmethod
    def state(self) -> dict: ...
    @abstractmethod
    def stop(self): ...
